@baseUrl={{$dotenv API}}
@testUrl={{$dotenv TEST}}
@email={{$dotenv EMAIL}}
@password={{$dotenv PASSWORD}}
@chatId={{$dotenv CHAT_ID}}
@messageId={{$dotenv MSG_ID}}
@userId0={{$dotenv U0_ID}}
@userId1={{$dotenv U1_ID}}
@userId2={{$dotenv U2_ID}}
@userId3={{$dotenv U3_ID}}

# @name test
GET {{testUrl}}/test/ HTTP/1.1
content-type: application/x-www-form-urlencoded

email={{email}}
&code={{$dotenv CODE}}

###

# @name createCode
POST {{baseUrl}}/codes/ HTTP/1.1
content-type: application/json

{
  "email": "{{email}}"
}

###

# @name createUser
POST {{baseUrl}}/users/ HTTP/1.1
content-type: application/json

{
  "code": "{{$dotenv CODE}}",
  "name": "{{$dotenv NAME}}",
  "surname": "Tester",
  "email": "{{email}}",
  "password": "{{password}}",
  "day": 29,
  "month": 10,
  "year": 1997,
  "sex": "{{$dotenv SEX}}"
}

###

# @name login
POST {{baseUrl}}/auth HTTP/1.1
content-type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###

# @name available
GET {{baseUrl}}/auth/?email={{email}} HTTP/1.1
content-type: application/json

###

@cookie = {{login.response.headers.set-cookie}}

# @name logout
DELETE {{baseUrl}}/auth HTTP/1.1
content-type: application/json
Cookie: {{cookie}}

###

# @name createMessage
POST {{baseUrl}}/messages HTTP/1.1
content-type: application/json
Cookie: {{cookie}}

# {
#   "users": [ "{{$dotenv U1_ID}}" ],
#   "body": "Hello. How are you?"
# }

# {
#   "users": [ "{{$dotenv U1_ID}}", "{{$dotenv U2_ID}}" ],
#   "body": "Hello everyone. How are you?"
# }

# {
#   "id": "{{chatId}}",
#   "body": "I'm good. And you?"
# }

###

# @name deleteMessage
DELETE {{baseUrl}}/messages/{{messageId}} HTTP/1.1
content-type: application/json
Cookie: {{cookie}}

###

# @name readChat
GET {{baseUrl}}/chats/{{chatId}} HTTP/1.1
content-type: application/json
Cookie: {{cookie}}

###

# @name updateChat
PUT {{baseUrl}}/chats/{{chatId}} HTTP/1.1
content-type: application/json
Cookie: {{cookie}}

{
  "photo": "#ff0000",
  "title": "ISTeam16",
  "_uids": [ "{{userId0}}", "{{userId1}}", "{{userId3}}" ],
  "_aids": [ "{{userId0}}", "{{userId1}}" ]
}

###

# @name listChats
GET {{baseUrl}}/chats HTTP/1.1
content-type: application/json
Cookie: {{cookie}}

###
